### ISSUE TITLE
request : please make a version for mocha

### ISSUE THREAD

**Issue by David-Else** [hustcc/jest-canvas-mock#10]
I am having a nightmare trying to mock the canvas using jsdom-global and mocha!

I run `mocha --reporter min --require esm --require jsdom-global/register -b` and it works great with jsdom, but as soon as it hits a canvas element i get `TypeError: Cannot read property 'getContext' of undefined`

In my test file I can write:
```
document.body.innerHTML =
  '<canvas width="500" height="500" id="canvas"></canvas>';
```
And it works, but I can't seem to write something like:

```
window.HTMLCanvasElement.prototype.getContext = () => {};
```
My jsdom is installed globally, and that seems to add to the headache. I tried everything, it is beyond me. Having a package to install that automated it would be awesome :)

**Comment by hustcc** [comment]
Sorry. I think you should learn how to write a plugin for mocha.

I have never use mocha for unit test.

**Comment by David-Else** [comment]
Fair enough.
