### ISSUE TITLE
Error with jest-canvas-mock and jest.resetAllMocks()

### ISSUE THREAD

**Issue by qiuhanWEI** [hustcc/jest-canvas-mock#103]
Hi, I'm using `jest.resetAllMocks()` in `afterEach` like this:

```typescript
afterEach(() => {
  jest.resetAllMocks();
});
```

and then, the first test case is successful but the following tests fail, because `context` is `undefined`:

```typescript
const canvas: HTMLCanvasElement = document.createElement('canvas');
const context: CanvasRenderingContext2D | null = canvas.getContext('2d');
```

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/25724621/196844481-497f9048-1bce-46b9-96f7-2f1d39207b9a.png">

I have to hack like this:
```typescript
import canvasMock from 'jest-canvas-mock/lib/mock/prototype';

afterEach(() => {
  jest.resetAllMocks();
});

beforeEach(() => {
  canvasMock();
});
```

Then all the test cases can be successful. But i still get an ERROR:

```
Could not find a declaration file for module 'jest-canvas-mock/lib/mock/prototype'
```

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/25724621/196845207-4aa27423-1cc6-4686-a5bc-83a4a9c6281f.png">

- **So My question is:**

**Is there a better way for us to use**  `jest-canvas-mock` with `jest.resetAllMocks()` ? 

Thanks!

**Comment by ducna-lts** [comment]
Have you found any solution yet, I have the same problem, don't know how to setup mock before start.

**Comment by qiuhanWEI** [comment]
Not yet.
I have to use the hack way `import canvasMock from 'jest-canvas-mock/lib/mock/prototype';`
and invoke `canvasMock` in `beforeEach`.

**Comment by qiuhanWEI** [comment]
> Have you found any solution yet, I have the same problem, don't know how to setup mock before start.

Not yet. @ducna-lts 
I have to use the hack way import canvasMock from 'jest-canvas-mock/lib/mock/prototype';
and invoke canvasMock in beforeEach.

**Comment by akphi** [comment]
Another way is to create a setup file

```js
// mockCanvas.js
import canvasMock from 'jest-canvas-mock/lib/mock/prototype.js';

beforeEach(() => {
  canvasMock();
});
```

and add that as a setup file in Jest config

```json
setupFilesAfterEnv: [
     'mockCanvas.js'
    ],
```

**Comment by pbomb** [comment]
@hustcc @nicks I'm running into this issue as well and see that it seems to have been resolved by #98 several months back. Any chance y'all could make another release to get this fix out? It's even more needed since Jest changed the behavior of the `restoreMocks` configuration that now removes the implementation of `jest.fn()` mocks after each test.

**Comment by pbomb** [comment]
@hustcc @nicks bumping to see if it might be possible to publish another version of this library. Thanks!

**Comment by nicks** [comment]
@pbomb i don't have any special publishing powers on this repo. if it helps, my team used `yarn patch` to downstream it into our repo without waiting on a release.

**Comment by hustcc** [comment]
+ jest-canvas-mock@2.5.0
