### ISSUE TITLE
node_modules/jest-canvas-mock/types/index.d.ts:1:54 - error TS1183: An implementation cannot be declared in ambient contexts.

### ISSUE THREAD

**Issue by jenilG** [hustcc/jest-canvas-mock#107]
I have this lint error being thrown by the typescript:
`node_modules/jest-canvas-mock/types/index.d.ts:1:54 - error TS1183: An implementation cannot be declared in ambient contexts.`

I have this when I am raising a PR in which I am upgrading below packages, will any of the below package bring this issue for jest-canvas-mock? Since it was not thrown before this PR

"immer": "^9.0.19" -> "immer": "^9.0.21"
"react-virtualized-auto-sizer": "^1.0.7" -> "react-virtualized-auto-sizer": "^1.0.9"
"webpack": "^5.76.3" -> "webpack": "^5.77.0"
"@cypress/code-coverage": "^3.10.0" -> "@cypress/code-coverage": "^3.10.1"
"@types/lodash": "^4.14.191" -> "@types/lodash": "^4.14.192"
"@types/node": "^14.18.40" -> "@types/node": "^14.18.42"
 "@types/react": "^16.14.35" -> "@types/react": "^16.14.37"

**Comment by michaelyu-aspentech** [comment]
I also faced this issue. There is no such error when I execute unit test with Jest, project build and debug, but when I run Storybook build it reports the error.
I remove node_module folder and re-run npm install, but still get the same error.
