### ISSUE TITLE
new `mockPrototype(win)` implementation can cause `TypeError`

### ISSUE THREAD

**Issue by virtuoushub** [hustcc/jest-canvas-mock#115]
I am running into an issue when upgrading to [`2.5.1`](https://renovatebot.com/diffs/npm/jest-canvas-mock/2.5.0/2.5.1) and I believe it has something to due with changes in #100.

```log
...
client:test: TypeError: Cannot read properties of undefined (reading 'prototype')
client:test:  ❯ mockPrototype ../../node_modules/.pnpm/jest-canvas-mock@2.5.1/node_modules/jest-canvas-mock/lib/mock/prototype.js:37:50
client:test:  ❯ Proxy._default ../../node_modules/.pnpm/jest-canvas-mock@2.5.1/node_modules/jest-canvas-mock/lib/window.js:61:26
client:test:  ❯ src/setupTests.ts:31:22
client:test:      [29](<code-under-test>/actions/runs/5090740096/jobs/9149933044?pr=1141#step:8:30)| ] as const;
client:test:      [30](<code-under-test>/actions/runs/5090740096/jobs/9149933044?pr=1141#step:8:31)| 
client:test:      [31](<code-under-test>/actions/runs/5090740096/jobs/9149933044?pr=1141#step:8:32)| const canvasWindow = getCanvasWindow({ document: window.document });
client:test:        |                      ^
client:test:      [32](<code-under-test>/actions/runs/5090740096/jobs/9149933044?pr=1141#step:8:33)| 
client:test:      [33](<code-under-test>/actions/runs/5090740096/jobs/9149933044?pr=1141#step:8:34)| apis.forEach((api) => {
...
```

looking at [the test case](https://github.com/hustcc/jest-canvas-mock/blob/master/__tests__/mock/window.js), it only covers when there is a wellformed window object.

Not sure what the expected behavior when something other than a wellformed window object is; however I was not seeing the above error in `2.5.0` and below. There seems to some delta between the global objects (`HTMLCanvasElement`, etc.) and this newly passed window object.

currently failing line: https://github.com/hustcc/jest-canvas-mock/blob/master/src/mock/prototype.js#L37

```js
...
  win.HTMLCanvasElement.prototype.getContext = getContext2D;
...
```

---

## suggestion

_suggestion_ - update the code to have this change be more conditional where we check if the passed in `win` object has the necessary props to not error in functions like `getContext2D`, and if it does not; fall back to the old behavior ( `mockPrototype()` ).

drawbacks, this potentially might be masking something in a project where the user expects the browser to behave one way; and due to all this mocking abstraction it behaves differently during testing. I think this is acceptable since, we are already basically doing this now, it just will behave slightly differently with the proposed suggestion than it does now, so I wanted to call it out.

_Originally posted by @virtuoushub in https://github.com/hustcc/jest-canvas-mock/issues/100#issuecomment-1564406609_

**Comment by Codex-** [comment]
Also running into this same problem:
```
TypeError: Cannot read properties of undefined (reading 'prototype')
 ❯ mockPrototype node_modules/jest-canvas-mock/lib/mock/prototype.js:37:50
 ❯ _default node_modules/jest-canvas-mock/lib/window.js:61:26
 ❯ importMockWindow node_modules/vitest-canvas-mock/dist/index.js:18:24
     16|   const getCanvasWindow = await import("jest-canvas-mock/lib/window.js").then((res) => res.default?.default |…
     17|   const canvasWindow = getCanvasWindow({ document: window.document });
     18|   apis.forEach((api) => {
       |                        ^
     19|     global[api] = canvasWindow[api];
     20|     global.window[api] = canvasWindow[API];
```

**Comment by virtuoushub** [comment]
> Also running into this same problem:
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'prototype')
>  ❯ mockPrototype node_modules/jest-canvas-mock/lib/mock/prototype.js:37:50
>  ❯ _default node_modules/jest-canvas-mock/lib/window.js:61:26
>  ❯ importMockWindow node_modules/vitest-canvas-mock/dist/index.js:18:24
>      16|   const getCanvasWindow = await import("jest-canvas-mock/lib/window.js").then((res) => res.default?.default |…
>      17|   const canvasWindow = getCanvasWindow({ document: window.document });
>      18|   apis.forEach((api) => {
>        |                        ^
>      19|     global[api] = canvasWindow[api];
>      20|     global.window[api] = canvasWindow[API];
> ```

temporary workaround is to downgrade to `2.5.0`

there is a fix for this out in #116 but it has not been reviewed/merged in yet. (cc @hustcc - can we get 👀  on #116 ?)

**Comment by Codex-** [comment]
> temporary workaround is to downgrade to `2.5.0`

`2.4.0` works 👌 

In my case, this is implicitly brought in by `vite-canvas-mock`, for now we're just not bumping it.

**Comment by ad1992** [comment]
I am facing the same issue as well when migrating to `vite-canvas-mock` however downgrading to `2.4.0` doesn't work for me
@Codex- whats your version for `jsdom`, `vite-canvas-mock` ?

**Comment by Codex-** [comment]
@ad1992 latest vite-canvas-mock, using an override for jest-canvas-mock:
https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides

**Comment by ad1992** [comment]
Yep I was able to make it work with `resolutions` as I am using `yarn`
https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/

Thanks so much @Codex-

**Comment by virtuoushub** [comment]
@hustcc gentle bump to get 👀 on #116 and merge/publish that fix as this should resolve the issues people are seeing.
