### ISSUE TITLE
Cannot install (operation not permitted)

### ISSUE THREAD

**Issue by folmert** [hustcc/jest-canvas-mock#12]
yarn add jest-canvas-mock:

>error An unexpected error occurred: "EPERM: operation not permitted,

**Comment by hustcc** [comment]
Give me more information.

**Comment by folmert** [comment]
What information specifically?

Newest yarn & node, Windows 10, running on Cmder with admin rights.

Full output:

> C:\Users\user\projects\FE\mine>yarn add jest-canvas-mock
> yarn add v1.3.2
> (node:39128) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> warning ..\..\package.json: No license field
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> info fsevents@1.2.4: The platform "win32" is incompatible with this module.
> info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
> [3/4] Linking dependencies...
> error An unexpected error occurred: "EPERM: operation not permitted, unlink 'C:\\Users\\user\\projects\\FE\\mine\\node_modules\\node-sass\\vendor\\win32-x64-64\\binding.node'".
> info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\user\\projects\\FE\\mine\\yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by folmert** [comment]
However, it does work when I add it to package.json, remove all node_modules and run `yarn install` again.

**Comment by hustcc** [comment]
Seem issue of yarn.
