### ISSUE TITLE
Request: Add CanvasPattern/CanvasGradient Support

### ISSUE THREAD

**Issue by FBNitro** [hustcc/jest-canvas-mock#13]
I'm using jest-canas-mock with openlayers.  I just hit an issue where OL is attempting to check if something is an instance of a CanvasPattern or CanvasGradient and the mock doesn't support it.

**Comment by hustcc** [comment]
Can you help me with a pr？

**Comment by hustcc** [comment]
What is your wasm？

**Comment by jtenner** [comment]
I can point to the problem!

It's here:

```ts
  quadraticCurveTo: () => {},
  createLinearGradient: () => ({
    // this function doesn't get wrapped
    addColorStop: () => {},
  }),
  createPattern: () => ({}),
  createRadialGradient: () => ({
    // this function doesn't get wrapped
    addColorStop: () => {},
  }),
```

**Comment by jtenner** [comment]
Also, because you are returning objects with wrapped functions, you cannot determine if they are of the correct class type.

`instanceof CanvasPattern` results in an error because `CanvasPattern` is not defined.

**Comment by jtenner** [comment]
If you'd like to see how I'm using jest-canvas-mock the source code is [here](https://github.com/as2d/as2d) in this repo.

**Comment by hustcc** [comment]
`1.1.1-beta.0` released, can help me test it in your case?

1.1.2 will release after you pass.

**Comment by jtenner** [comment]
Hey this is great! Is there a possibility that you could also export a `CanvasRenderingContext2D` class as well that functions exactly like the `CanvasPattern` and `CanvasGradient` class as well?

**Comment by jtenner** [comment]
I would really like to test my values using `instanceof`

**Comment by jtenner** [comment]
If you would like I can probably submit a pull request so that all the transform functions modify the `currentTransform` property too.

**Comment by hustcc** [comment]
ok, send your pull request.

**Comment by jtenner** [comment]
This could take a very long time.

**Comment by hustcc** [comment]
Why you need to export the mock Canvas2D class？

the new beta version can not satisfy yours？

**Comment by hustcc** [comment]
ok

**Comment by jtenner** [comment]
@hustcc I have created a fork of the project and will submit a pull request with a propert CanvasRenderingContext2D class that does a *lot* more than just verify functions were called.

Later this afternoon I will submit a pull request so you can follow along and make sure everything is up to your standards.
