### ISSUE TITLE
Missing index.js

### ISSUE THREAD

**Issue by xieqingtian** [hustcc/jest-canvas-mock#14]
errorMessage  
`Module jest-canvas-mock in the setupFiles option was not found.`  
![image](https://user-images.githubusercontent.com/20181476/51421701-0f4df380-1bdd-11e9-8efe-2f51dd957ea8.png)

**Comment by hustcc** [comment]
upgrade to

+ jest-canvas-mock@1.1.1-beta.1

or, do not use beta version.
