### ISSUE TITLE
createImageData() returns wrong type

### ISSUE THREAD

**Issue by robinelvin** [hustcc/jest-canvas-mock#15]
My code uses [node-qrcode](https://github.com/soldair/node-qrcode) to generate a QR code in a canvas. It calls `createImageData()` and then tries to use the `data` property of the returned object which fails with:

`TypeError: Cannot set property '0' of undefined`

node-qrcode accesses the data property here: [canvas.js#L39](https://github.com/soldair/node-qrcode/blob/master/lib/renderer/canvas.js#L39)

The current mock implementation is:

[context2d.js#L22](https://github.com/hustcc/jest-canvas-mock/blob/master/src/classes/context2d.js#L22)
```javascript
createImageData: () => [],
```

I think it should follow the spec at [MDN - createImageData()](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createImageData)

When I change the code to the following my test works:

```javascript
createImageData: () => {width: 1, height: 1, data: []},
```

I'm not sure if the dimensions should be set to anything in particular but the above works for my case.

**Comment by hustcc** [comment]
Yes, you are right, can help me with a pull request?

**Comment by jtenner** [comment]
@hustcc I have actually covered this in my pull request. Can you take a look and let me know what you think?

**Comment by jtenner** [comment]
This is all set! #17 closes this. #20 has better testing support for it.

**Comment by robinelvin** [comment]
Latest 2.0.0-alpha.0 has created a different error.

```console
    TypeError: ctx.createImageData is not a function

      51 |         const canvasElement = ReactDOM.findDOMNode(this.canvas);
      52 |         // Generate QR code svg
    > 53 |         QRCode.toCanvas(canvasElement, this.props.qrCodeUrl);
         |                ^
      54 |     }
      55 | 
      56 |     public render() {
```

**Comment by jtenner** [comment]
@robinelvin My appologies! I will implement this function right away. This is why @hustcc released this as an alpha. 

I have added a test suite in the next pull request for what will likely be `alpha.1` that properly tests the `createImageData` function.
