### ISSUE TITLE
Update jest to v24

### ISSUE THREAD

**Issue by jtenner** [hustcc/jest-canvas-mock#18]
I can do this in my pull request. Please advise?

**Comment by hustcc** [comment]
ok, just do it.

**Comment by jtenner** [comment]
Is there any way I can message you?

**Comment by hustcc** [comment]
wechat or email？

**Comment by jtenner** [comment]
Wechat is fine. Can you use my email to find me? Tenner.joshua@gmail.com

**Comment by jtenner** [comment]
How may I find you?

**Comment by jtenner** [comment]
I am jtenner on wechat now.
