### ISSUE TITLE
Consider adopting a CHANGELOG

### ISSUE THREAD

**Issue by erickwilder** [hustcc/jest-canvas-mock#30]
Currently, the only way to figure it out breaking (or important) changes is by searching and comparing commits. It would be very helpful if a `CHANGELOG` file was annotated with important changes made in the code base.

**Comment by erickwilder** [comment]
Related to that, keeping versions as `git` tags would also make it easier to compare revisions.

**Comment by hustcc** [comment]
thanks, will do it after v2.0.0 released.

**Comment by jtenner** [comment]
@hustcc How do you think we should do a changelog?

**Comment by erickwilder** [comment]
I've been using [semantic-release](https://github.com/semantic-release/semantic-release) for some private projects and it works quite well. The only "downside" is that it gets picky with your commit messages as they end up in the changelog as well.

**Comment by jtenner** [comment]
2.0.0 is such a breaking change, and honestly I was just planning on doing a write up of each function. All the commits at this point couldn't do the amount of work I've done justice in explaining what jest-canvas-mock does now.

**Comment by jtenner** [comment]
@hustcc have we added a beta tag?

**Comment by hustcc** [comment]
done!
