### ISSUE TITLE
Method to log commands to context and snapshot test?

### ISSUE THREAD

**Issue by cmdcolin** [hustcc/jest-canvas-mock#33]
Hello, I was wondering if it is possible to use this library to log the drawing commands submitted to a context and retrieve them as a list.

Thanks

**Comment by jtenner** [comment]
Yes. This is possible. I'm not sure how to use snapshots though.

What kind of interface are you looking for?

**Comment by cmdcolin** [comment]
I don't have a lot of experience with mocking. if it can maybe augment the canvas or context to retrieve the drawn commands that seems reasonable? My setup is I have a method that performs server side rendering and calls toimagedata or createimagebitmap depending on environment support

**Comment by jtenner** [comment]
I went and looked up snapshots. I'll need a day to think about this, because i can think of at least 2 different ways to collect data about the function calls.

**Comment by jtenner** [comment]
@cmdcolin I have two solutions. We can simulate "draw calls" or/and we can simulation "function calls".

```ts
// get only the successful draw calls
expect(CanvasRenderingContext2D.__getDrawCalls(ctx)).toMatchSnapshot(); 
// get every operation performed on the context
expect(CanvasRenderingContext2D.__getOperations(ctx)).toMatchSnapshot(); 
```

**Comment by jtenner** [comment]
I think these examples are poorly written. Let's make this into a more concrete specification. We can take the following TypeScript interface as an example.

```ts
interface CanvasRenderingContext2DDrawCall {
  operationType: "drawImage" | "fillRect" | "fill"; // etc
  path: Path2DElement[];
  transform: [number, number, number, number, number, number];
  parameters: {
    [name: string}: any;
  };
}
```

Whenever a function call would actually result in a draw call, it should be pushed to an array that can be used for immutable snapshots.

I don't exactly know what the function should be named, but the following example should work just fine.

```ts
const drawCalls: CanvasRenderingContext2DDrawCall[] = __getDrawCalls(ctx):
expect(drawCalls).toMatchSnapshot();
```

We can also use information about events that occur within the canvas context, like if a property was set, or the `save()` function was called.  Take the following interface for example:

```ts
interface CanvasRenderingContext2DEvent {
  type: string;
  transform: [number, number, number, number, number, number]; // the resulting current transform
  props: {
     [propName: string]: any; // if the event is a property was set, `event.props.value` would be set
  };
}

**Comment by jtenner** [comment]
I've started work on this issue. It's going to take a very long time, because I want to verify the output of these function for *each* canvas function and operation.

**Comment by jtenner** [comment]
This is currently how the testing suite verifies `__getEvents(ctx)` output. It should match your needs when it is done. :)

```ts
let ctx;
beforeEach(() => {
  ctx = document.createElement("canvas").getContext("2d");
});
afterEach(() => {
  expect(CanvasRenderingContext2D.__getEvents(ctx)).toMatchSnapshot();
});
describe("something", () => {
  // test your canvas calls here
});
```

@cmdcolin does this suffice?

**Comment by cmdcolin** [comment]
I'm fairly certain this will be fine. I just read through your above definition of what the event object looks like and I think that looks good too!

**Comment by jtenner** [comment]
Feel free to try out the `mock-support` branch @cmdcolin.

**Comment by jtenner** [comment]
A huge feature addition should probably be a minor release. Also, I will wait until @cmdcolin tries the branch.

**Comment by cmdcolin** [comment]
Thanks for this. I did some cursory poking at it

I noticed a small thing that a command in the readme is checking for the wrong exception possibly

```
    Expected name: "TypeError"                                                                                                                           
    Received name: "Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-10) is negative."                                       
                                                                                                                                                         
    Received message: "IndexSizeError"                                                                                                                   
                                                                                                                                                         
          3 |   const ctx = canvas.getContext('2d')                                                                                                      
          4 |   expect(() => ctx.arc(1, 2, 3, 4)).toThrow(TypeError);                                                                                    
        > 5 |   expect(() => ctx.arc(0, 0, -10, 0, Math.PI * 2)).toThrow(TypeError); 
```
That appears on master too. I wasn't sure how to reference IndexSizeError istead


Regarding the PR I can see that "expect(CanvasRenderingContext2D.__getOperations(ctx)).toMatchSnapshot(); " was proposed in an above comment, is it now getEvents? other than that, I tested just a couple random things myself and looked at the tests in the PR

**Comment by jtenner** [comment]
> I noticed a small thing that a command in the readme is checking for the wrong exception possibly

Yes, that would be a `DOMException` error.

> Regarding the PR I can see that "expect(CanvasRenderingContext2D.__getOperations(ctx)).toMatchSnapshot(); " was proposed in an above comment, is it now getEvents? other than that, I tested just a couple random things myself and looked at the tests in the PR

Ah yes, I changed the name to be terser.

If you think it looks good, I can pull the request.
