### ISSUE TITLE
getContext() should be idempotent

### ISSUE THREAD

**Issue by kevinbarabash** [hustcc/jest-canvas-mock#34]
I have some code that uses an old jQuery plugin and it ends up calling `getContext()` more than once one the same Canvas element.  This works fine in the browser with the real Canvas element.  This causes `_stackIndex` along with all of the other internal instance variables in CanvasRenderingContext2D.js to be reset when they shouldn't be.  This should be pretty easy to fix by adding a Symbol to the Canvas element containing the context from `getContext()` and then checking if that Symbol exists (and returning it) whenever `getContext()` is called.  Would you be interested in a pull request for this issue?

**Comment by jtenner** [comment]
Sounds great! I bet this can be done with a single weakmap though.

**Comment by jtenner** [comment]
I dont want to duplicate work. Are you going to work on this?

**Comment by jtenner** [comment]
Please see #35 for a fixed version. Can you try it out in your project @kevinbarabash?

**Comment by kevinbarabash** [comment]
@jtenner I was planning on working on this but you beat me to it.  I'll try it out.

**Comment by kevinbarabash** [comment]
I tested it out using `npm link` and my test case is now passing.  Thank you.
