### ISSUE TITLE
Webpack importing package?

### ISSUE THREAD

**Issue by th3fallen** [hustcc/jest-canvas-mock#4]
Not sure what's causing this but webpack is building this package into my bundle dispite it only being used in setupScripts? i get an error about jest not being defined.

Am i missing something stupid?

**Comment by hustcc** [comment]
Show me your usage, version, error message…

**Comment by th3fallen** [comment]
usage, 
```"setupFiles": [
      "raf/polyfill",
      "<rootDir>/scripts/testSetup.js",
      "jest-canvas-mock"
    ],
```

version └─ jest-canvas-mock@1.0.2

error message is https://cl.ly/qIMT/Image%202018-03-19%20at%201.04.45%20PM.png

**Comment by hustcc** [comment]
npm install jest

**Comment by th3fallen** [comment]
we have jest installed, the issue is that warning is appearing in the built app where this binary has no business being...

**Comment by hustcc** [comment]
How can it be!

Can you give me more information about your code, or check whether import `jest-canvas-mock` in all of your code?

**Comment by th3fallen** [comment]
i found the issue, when i installed it i didnt install it as a dev dep which made webpack grab it for my vendor bundle
