### ISSUE TITLE
Use with OffscreenCanvas?

### ISSUE THREAD

**Issue by cmdcolin** [hustcc/jest-canvas-mock#42]
Hi there,
I am trying to test OffscreenCanvas in an app. Is this something that jest-canvas-mock can help with or is there a type of thing that should be handled separately?

**Comment by jtenner** [comment]
Definitely. I need some time to figure out how to implement this.

**Comment by jtenner** [comment]
Are you planning on using this across threads for your testing? I don't think we can mock a transferable object.

**Comment by cmdcolin** [comment]
I will probably just use in single thread at moment. Our usage of offscreen canvas is for multithread but we have single thread running modes too

**Comment by jtenner** [comment]
When another thread is used, the mocking library can't run because jsdom doesn't exist there.

It's possible to mock transferControlToOffscreen() though.

I can't exactly get around to this for a week or so.

**Comment by jtenner** [comment]
Hey! This issue is getting stale, and after a long time to think about this problem, I'm not sure this should or could be done without many caveats and playing with developer expectation.

We can't get multithreaded support and it might just be better to add a `commit()` function to the `CanvasRenderingContext2D` class.

Are you opposed to this?

**Comment by jtenner** [comment]
Another hacky solution could be to use `ctx.commit = () => void 0;`.

You could require the `CanvasRenderingContext2D` class *on another thread* via...

```ts
const CanvasRenderingContext2D = require("jest-canvas-mock/lib/CanvasRenderingContext2D");
const ctx = new CanvasRenderingContext2D(); // use this object

```

The only thing you won't be able to use is `ImageData` via `.getImageData()`. That requires a canvas element. You would have to mock something in the constructor that has a `{ height: number; width: number; }` shape in the constructor.

**Comment by jtenner** [comment]
This issue is stale. It can be fixed pretty much with the above fixes. Any other comments?

**Comment by cmdcolin** [comment]
I'm fine with closing for now. This is my postmortem that I posted to a jest-dom thread about my workaround, my whole aim was to get a large scale integration test and it just happened that I thought about testing canvas rendering in detail after finding this library but I kind of scaled that back.

I am now just using the normal jest canvas testing without jest-canvas-mock https://github.com/jsdom/jsdom/issues/1782#issuecomment-504242684

**Comment by cmdcolin** [comment]
In case it helps to see the weird stuff we do in practice it is this https://github.com/GMOD/jbrowse-components/blob/e3463d0f651deb65e50c8dc4c766646b6b217287/packages/core/util/offscreenCanvasPonyfill.js

**Comment by cmdcolin** [comment]
My whole aim was to actually allow our fake createImageBitmap to work with this library which was difficult

**Comment by jtenner** [comment]
Ah. Well that could certainly be improved. What was the problem with create Image Bitmap?

**Comment by cmdcolin** [comment]
I can't quite recall but it was sort of similar to what looks like this https://github.com/hustcc/jest-canvas-mock/pull/26/files except you can see my code produces an Image instead of an ImageBitmap or Blob I think...kind of weird

**Comment by jtenner** [comment]
Yeah the problem is that jsdom doesn't make things like this easy. So you need to support a different class type?

```ts
createImageBitmap.extend(MyClass, (...props) => {
  return new ImageBitmap(width, height);
});
```

I would not mind supporting something like this. Often, I've found that things like this get in the way of testing, and I would personally find it useful.

Any thoughts?

**Comment by hustcc** [comment]
For full dom environment, you can just have a try with [jest-electron](https://github.com/hustcc/jest-electron) which run and debug test case in real browser.

mock is just for test, but not debug.

**Comment by cmdcolin** [comment]
No worries, thanks for your patience. I'll close for now maybe then :)
