### ISSUE TITLE
Add ability to clear event lists

### ISSUE THREAD

**Issue by andypearson** [hustcc/jest-canvas-mock#48]
Hello! First of all, thank you so much for writing and releasing this library. I am trying to build a Photoshop like editor that uses `<canvas>` for rendering and I have no idea how I would have tested it without the help of `jest-canvas-mock`!

In the interface I am building the user can add layers to the canvas, and the canvas automatically updates for each layer that is added.

What I would like to do is compare a snapshot of the final canvas state, but not the interim states where the user hasn't finished adding layers.

The way I was thinking about doing it was to clear the set of events before the final layers is added in the test, and then take a snapshot of the result. At the moment it is not possible to clear the recorded events on the context, as those are stored internally.

What would be handy would be a matching set of `clear` methods for the current API:

* `__clearEvents`
* `__clearPath`
* `__clearDrawCalls`

These would clear the corresponding internal arrays.

Does this sound like it would be a useful addition to the library? If so, I could try and scrabble together a PR.

Alternatively, do you think there is another way of approaching my requirement?

**Comment by hustcc** [comment]
You can consider using [jest-electron](https://github.com/hustcc/jest-electron) for dom test at first.

If not work for you, then give us a pr with discussion.

**Comment by jtenner** [comment]
I am open to supporting this. The easiest and quickest way to do this is to set the internal array lengths to `0`.  This would be _fastest_. Securest way would likely to be setting the array to `[]`.

If you would would like to submit a pr, we can do a minor release because supporting this api would not be breaking to old apis.
