### ISSUE TITLE
Release v2.2.0

### ISSUE THREAD

**Issue by jtenner** [hustcc/jest-canvas-mock#55]

**Comment by hustcc** [comment]
@jtenner What's your npm account?

I think your contribution to this repo is far more than mine. You should be the owner of this repo and module. You can publish this module by yourself.

**Comment by jtenner** [comment]
Feel free to transfer the entire repo to me if you feel I deserve it.

Here is my npm account:
https://www.npmjs.com/~jtenner

**Comment by hustcc** [comment]
@jtenner added.

**Comment by jtenner** [comment]
Thank you. This was helpful.
