### ISSUE TITLE
[with solution]: incorrect event value stored for context.setTransform ()

### ISSUE THREAD

**Issue by tmarti** [hustcc/jest-canvas-mock#56]
If we look at the following code from `setTransform` method...

https://github.com/hustcc/jest-canvas-mock/blob/b836a8d11a55a15ab5f7f0323c6272d708fc6358/src/classes/CanvasRenderingContext2D.js#L1230-L1234

... we see that the value property of the event is provided as `{ a, b, c, d, e, f }`.

If we type in the javascript console:

`{ 1, 2, 3, 4, 5, 6 }`

We get this output:

`6`

Comparing the code to that of the `resetTransform` method...

https://github.com/hustcc/jest-canvas-mock/blob/b836a8d11a55a15ab5f7f0323c6272d708fc6358/src/classes/CanvasRenderingContext2D.js#L1031-L1040

If we type in the javascript console:

`{ a: 1, b: 2, c: 3, d: 4, e: 5, f: 6}`

We get this output:

`{ a: 1, b: 2, c: 3, d: 4, e: 5, f: 6}`

So, it seems that this line...

https://github.com/hustcc/jest-canvas-mock/blob/b836a8d11a55a15ab5f7f0323c6272d708fc6358/src/classes/CanvasRenderingContext2D.js#L1233

... should be changed to:

`{ a: a, b: b, c: c, d: d, e: e, f: f}`

**Comment by jtenner** [comment]
No. That is incorrect.

```ts
const object = { a, b, c, d, e, f };
```

This is valid javascript that is the same thing as:

```ts
const object = { a: a, b: b, c: c, d: d, e: e, f: f };
```

I understand you want to be helpful, and you've pointed out two very valid problems with my software, which is great.

This particular problem you've identified is valid JS syntax that is the equivalent of what you have proposed as the solution.  If you have any further questions, you can leave this issue open but I intend on closing it as a non-issue.

**Comment by jtenner** [comment]
By the way, if you type `{ 1, 2, 3, 4, 5, 6 }` into the console, what the console interprets that as is a `BlockStatement` that contains a single expression which is `1, 2, 3, 4, 5, 6`.

That comma separated expression yields a `6`. You can type `1, 2, 3, 4, 5, 6` into the console and it will output 6.

Try typing:

```
const a = 1;
const a = 1;
const a = 1;

**Comment by tmarti** [comment]
Oh! Many thanks! Everyday I learn something new 😉

El dc., 6 nov. 2019, 16:33, jtenner <notifications@github.com> va escriure:
