### ISSUE TITLE
Usage with Jest 23?

### ISSUE THREAD

**Issue by Nfinished** [hustcc/jest-canvas-mock#61]
Is there an older version compatible with Jest 23? The oldest release looks like it uses 24.

**Comment by jtenner** [comment]
I believe there is. Is there a reason why you can't switch to jest 24?

**Comment by Nfinished** [comment]
Yeah, I'm unfortunately not in a position to make that decision.

**Comment by jtenner** [comment]
Okay. Try using jest 23 with this software, and see what happens. Does it come up with an error?

**Comment by Nfinished** [comment]
I could be missing something,Jest23 is reporting that `setupFiles` is unavailable, is that just my environment and not a compatibility issue?

**Comment by jtenner** [comment]
Possibly. What version of Jest are you locked into exactly?

**Comment by Nfinished** [comment]
23.6.0

**Comment by jtenner** [comment]
I should be able to look at this today. `jest-canvas-mock` had some growing pains when it switched to 24 compatibility. I'll run the test suite soon.

Thanks for opening up this issue!

**Comment by hustcc** [comment]
@Nfinished Maybe upgrade jest is the best way, has a try
