### ISSUE TITLE
Not recognising 'transparent' colour

### ISSUE THREAD

**Issue by evanoc0** [hustcc/jest-canvas-mock#64]
Drawing a linear gradient which trails off to transparency using this code:
```js
    this.ctx = this.canv.current.getContext("2d");
    const gradient = this.ctx.createLinearGradient(x1, y1, x2, y2);
    gradient.addColorStop(0.0, this.state.colour);
    gradient.addColorStop(0.925, this.state.colour);
    gradient.addColorStop(1.0, "transparent");
    this.ctx.fillStyle = gradient;
    this.ctx.fillRect(x1, y1, w, h);
```

The above renders fine in Firefox, but is unable to build in the unit tests, caused by this error:
<img width="980" alt="Screenshot 2020-04-08 at 13 10 05" src="https://user-images.githubusercontent.com/14321104/78782697-4e12c980-799a-11ea-85b5-8155405d3188.png">

After initially looking into it, I presume this is an issue to do with the [parse-color](https://www.npmjs.com/package/parse-color) module you are using, but it is quite old.

Is there a possibility of changing the library being used for this?

**Comment by jtenner** [comment]
Hey! Thanks for posting this issue. Perhaps we do need a css color parser compliant to the spec.

Are there any alternatives?

**Comment by evanoc0** [comment]
I looked around a bit and couldn't find anything immediately helpful for this, but I think it could be handled easily. Take a look at my solution to it [here](https://github.com/hustcc/jest-canvas-mock/pull/65)
