### ISSUE TITLE
measureText returns number of characters rather than computed length  

### ISSUE THREAD

**Issue by evargast** [hustcc/jest-canvas-mock#67]
<img width="773" alt="Screen Shot 2020-05-12 at 11 50 22 AM" src="https://user-images.githubusercontent.com/52969178/81722602-39b56700-9447-11ea-90df-876feecbd264.png">

**Comment by jtenner** [comment]
Correct. `jest-canvas-mock` is a mock library, not a canvas implementation, and it doesn't return actual text measurements. It would have to actually figure out how wide the text is based on font rendering.

I believe this is out of the scope of the mocking project, unless someone else can pick up the responsibility to maintain font rendering measurement calculations.

In the meantime, a nice workaround might be:

```ts
ctx.measureText.mockReturnValueOnce(thePreCalculatedValue);
```

**Comment by evargast** [comment]
Ah I see, thank you!

**Comment by danvoyce-warner** [comment]
I think at the least it would be great to put a `console.warn` or something to make it clear whats happening when this gets called, rather than poor souls like us spending hours debugging then eventually ending up here (if we're lucky!)

**Comment by jtenner** [comment]
@danvoyce-warner that sounds like a great idea. I accept pull requests.

**Comment by danvoyce-warner** [comment]
Just thinking about this, what if we made it (for example) 5px per character? This would at least solve our use case. At the same time adding some logging to explain what's going on.

**Comment by jtenner** [comment]
Sounds fine to me
