### ISSUE TITLE
What's the difference between jest-canvas-mock and node-canvas?

### ISSUE THREAD

**Issue by atav32** [hustcc/jest-canvas-mock#68]
[jsdom's documentation](https://github.com/jsdom/jsdom#canvas-support) suggests using the [`canvas`](https://www.npmjs.com/package/canvas) package (also called node-canvas).

What's the difference between this package and node-canvas?

**Comment by kidkkr** [comment]
This library wraps up the Canvas API with jest mocks. (Does not implements `Canvas` at all)
