### ISSUE TITLE
getImageData returns undefined

### ISSUE THREAD

**Issue by danielrentz** [hustcc/jest-canvas-mock#82]
This code line fails in Jest, because getImageData returns undefined:

```js
    const pixel = context.getImageData(1, 1, 1, 1).data;
```

**Comment by jtenner** [comment]
Yep. You need to mock the return value.

**Comment by danielrentz** [comment]
Hi! Thanks ... ok I see I have to look how this entire mocking thing works (I'm new to Jest). Is there a list with methods that need to be mocked, that could be added to the README? I saw the short "Override default mock return value" about "toDataURL" and thought this is somewhat optional or special.

**Comment by danielrentz** [comment]
For the records: The root cause was the settings `resetMocks: true` in my Jest config. From the second test on, all default mocks created by jest-canvas-mock are vanishing with this setting...

**Comment by jtenner** [comment]
Ah yeah that will do it. Glad you found the issue.
