### ISSUE TITLE
What's the difference between jest-canvas-mock and canvas?

### ISSUE THREAD

**Issue by shayantabrizi** [hustcc/jest-canvas-mock#87]
What's the difference between `jest-canvas-mock` and `canvas`?
In fact, `canvas` is suggested in the error message:

> Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)

**Comment by wobsoriano** [comment]
Just install jsdom as it comes with canvas already

**Comment by hustcc** [comment]
`canvas` is canvas implementation for [Node.js](http://nodejs.org/), but `jest-canvas-mock` is just mocker for jest.

- `canvas` can draw image in nodejs
- `jest-canvas-mock` just avoid error in jest
