### ISSUE TITLE
Vitest configuration

### ISSUE THREAD

**Issue by wobsoriano** [hustcc/jest-canvas-mock#88]
Not really an issue but if you come here looking for vitest solution, here's my configuration:

```ts
// vitest.config.ts
import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    setupFiles: ['./vitest.setup.ts'],
    environment: 'jsdom',
    threads: false,
    environmentOptions: {
      jsdom: {
        resources: 'usable',
      },
    },
  },
})
```

```ts
// vitest.setup.ts
import { afterAll, vi } from 'vitest'
// @ts-expect-error: type
global.jest = vi
// eslint-disable-next-line import/first
import getCanvasWindow from 'jest-canvas-mock/lib/window'

const apis = [
  'Path2D',
  'CanvasGradient',
  'CanvasPattern',
  'CanvasRenderingContext2D',
  'DOMMatrix',
  'ImageData',
  'TextMetrics',
  'ImageBitmap',
  'createImageBitmap',
] as const

const canvasWindow = getCanvasWindow({ document: window.document })

apis.forEach((api) => {
  // @ts-expect-error: type
  global[api] = canvasWindow[api]
  // @ts-expect-error: type
  global.window[api] = canvasWindow[api]
})

afterAll(() => {
  // @ts-expect-error: type
  delete global.jest
  // @ts-expect-error: type
  delete global.window.jest
})
```

**Comment by jagoncalves14** [comment]
This is awesome! @wobsoriano 👏

Thanks to you, I added this to my code but on a separate setup file, which I called `vitest-canvas-mock.ts`.

```
// vitest-canvas-mock.ts
// @ts-ignore
global.jest = vi

import getCanvasWindow from 'jest-canvas-mock/lib/window'

const canvasWindow = getCanvasWindow({ document: window.document })
const apis = [
  'Path2D',
  'CanvasGradient',
  'CanvasPattern',
  'CanvasRenderingContext2D',
  'DOMMatrix',
  'ImageData',
  'TextMetrics',
  'ImageBitmap',
  'createImageBitmap',
] as const

apis.forEach(api => {
  global[api] = canvasWindow[api]
  global.window[api] = canvasWindow[api]
})

afterAll(() => {
  delete global.jest
  delete global.window.jest
})
```

And then I imported it in the vite.config.ts' `setupFiles`:

```
// vitest.config.ts
import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    setupFiles: ['./vitest.setup.ts', './vitest-canvas-mocks.ts'],
    environment: 'jsdom',
    threads: false,
    environmentOptions: {
      jsdom: {
        resources: 'usable',
      },
    },
  },
})
```

**Comment by wobsoriano** [comment]
Published a simple module for this 

https://github.com/wobsoriano/vitest-canvas-mock

**Comment by estebancl89** [comment]
Thanks for this @wobsoriano . I am getting this error? 

`ReferenceError: jest is not defined
 ❯ Object.<anonymous> node_modules/.pnpm/jest-canvas-mock@2.5.2/node_modules/jest-canvas-mock/lib/mock/createImageBitmap.js:9:16
 ❯ Object.<anonymous> node_modules/.pnpm/jest-canvas-mock@2.5.2/node_modules/jest-canvas-mock/lib/window.js:16:49`

**Comment by BacLuc** [comment]
> Thanks for this @wobsoriano . I am getting this error?
> 
> `ReferenceError: jest is not defined ❯ Object.<anonymous> node_modules/.pnpm/jest-canvas-mock@2.5.2/node_modules/jest-canvas-mock/lib/mock/createImageBitmap.js:9:16 ❯ Object.<anonymous> node_modules/.pnpm/jest-canvas-mock@2.5.2/node_modules/jest-canvas-mock/lib/window.js:16:49`

It may be a race condition.
I ran the https://github.com/ecamp/ecamp3 10 times,
and 5/10 failed.
https://github.com/BacLuc/ecamp3/actions/runs/6996753460/job/19032983059

**Comment by xavierfacq** [comment]
> I am getting this error? ReferenceError: jest is not defined ❯ Object.<anonymous> node_modules/.pnpm/jest-canvas-mock@2.5.2/node_modules/jest-canvas-mock/lib/mock/createImageBitmap.js:


Hello, I have the same random error on my project. Did you find a solution? thx !

**Comment by Bushuo** [comment]
I found this issue, maybe it helps: https://github.com/vitest-dev/vitest/issues/2667

**Comment by xavierfacq** [comment]
I think we have solved the problem by just adding the following line to the file `vitest-setup.ts`

`import 'jest-canvas-mock';`


FYI we have the following version:

```
"jest-canvas-mock": "^2.5.2"
"vitest-canvas-mock": "^0.3.3"
```
