### ISSUE TITLE
Test fails on Node.js 18

### ISSUE THREAD

**Issue by LitoMore** [hustcc/jest-canvas-mock#89]
The `npm test` fails on Node.js 18.

BTW, versions in `.travis.yml` need to be updated.

### How to reproduce

```shell
cd jest-canvas-mock
nvm use 18
npm test
```

This error message below will show up from all tests:

```shell
TypeError: Cannot redefine property: window
```

**Comment by LitoMore** [comment]
I created a PR to update our `.travis.yml`. See https://github.com/hustcc/jest-canvas-mock/pull/90

**Comment by jacklovett** [comment]
Is there an ETA on when we can see this in a new version? Currently having this issue

**Comment by LitoMore** [comment]
> Is there an ETA on when we can see this in a new version? Currently having this issue

There will be a new version soon. I have notified the author via direct message.

**Comment by hustcc** [comment]
v2.4.0 released.
