### ISSUE TITLE
How to import types ?

### ISSUE THREAD

**Issue by emmanuelgeoffray** [hustcc/jest-canvas-mock#99]
I tried 
```
import type { CanvasRenderingContext2D } from 'jest-canvas-mock'
```
and
```
import type { CanvasRenderingContext2D } from 'jest-canvas-mock/types'
```
but CanvasRenderingContext2D is not an exported member.

I've also tried to `npm i --save-dev @types/jest-canvas-mock` without success.

Is there an other way to import types ?

**Comment by hustcc** [comment]
You should import dom type from other types pkg.
